[placeholders.plugin_name]
type = "string"
prompt = "What is the name of this plugin package? (will automatically be prefixed by nu_plugin_)"

[placeholders.plugin_struct]
type = "string"
prompt = "What should we call the plugin struct? (Thing that implements nu_plugin::Plugin)"
default = "Implementation"
